[project]
name = "python-expertise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "load-dotenv>=0.1.0",
    "pymongo>=4.15.5",
    "requests>=2.32.5",
]
